export const ADD_TASK = "ADD_TASK";
export const TOGGLE_TASK = "TOGGLE_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const COMPLETED_TASK = "COMPLETED_TASK";
export const UNCOMPLETED_TASK = "UNCOMPLETED_TASK";

export const FILTER_TASK = "FILTER_TASK";

export const MARK_ALL_COMPLETED = "MARK_ALL_COMPLETED";

export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
